version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: proguard-with-maven-example-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: proguard-with-maven-example-{{ checksum "pom.xml" }}
      - run: mvn package
