version: 2
jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: proguard-with-maven-example-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: proguard-with-maven-example-{{ checksum "pom.xml" }}
      - run: mvn package
  jdk11:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: proguard-with-maven-example-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: proguard-with-maven-example-{{ checksum "pom.xml" }}
      - run: mvn package
workflows:
  version: 2
  work:
    jobs:
      - jdk8
      - jdk11
